### ISSUE TITLE
Question regarding when to use fix_oralib.rb vs symlinking to ~/lib

### ISSUE THREAD

**Issue by brightredchilli** [kubo/fix_oralib_osx#5]
Hi kubo, I'm reaching you here more for a question, and not as an issue with the library.

I have been running into problems with cx_oracle and your ruby library definitely helped me fix it. However, after reading thread: https://github.com/oracle/node-oracledb/issues/149#issuecomment-170711705, and the Apple doc referenced inside: https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/UsingDynamicLibraries.html I became more convinced that the right thing to do is to create symlinks from the client install path to ~/lib. I was wondering if you had thoughts on this, or maybe want to update the documentation on when we'd want to use fix_oralibs.rb over this.

Thanks for the great library!

**Comment by kubo** [comment]
Sorry for not replying for a long time. It needs energy for me to write documents in English...

Oracle released Oracle instant client 12.1, which supports El Capitan natively. So fix_oralib.rb is not needed anymore.

**Comment by kubo** [comment]
FYI. The environment variable `FORCE_RPATH` should be set to compile cx_Oracle with the 12.1 client.

In http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html
> Note: Custom applications should link with -rpath set to the directory containing Instant Client 12.1.
